# security logging level
logging:
  level:
    org:
      springframework:
        security: TRACE

#data base
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_bank?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-test-query: SELECT 1
      pool-name: HikariCP-Pool

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
